<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Sublime Hg CLI (New)</string>
	<key>patterns</key>
	<array>
	</array>
	<key>scopeName</key>
	<string>source.sublime_hg_cli</string>
	<key>uuid</key>
	<string>d9e5ff0a-4258-4475-be50-2d7554d407f8</string>
</dict>
</plist>
