<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>SublimeHg Command Line</string>
	<key>scopeName</key>
	<string>text.sublimehgcmdline</string>
	<key>uuid</key>
	<string>9880a5b1-a545-4113-bc56-1466904e5ba5</string>
</dict>
</plist>
